version: "3.4"

services:
  api:
    build:
      context: ./api
      args:
        - API_HOST=${API_HOST}
        - API_PORT=${API_PORT}
    ports:
      - "${API_PORT}:8000"
    volumes:
      - ./api/:/usr/src/api
    depends_on:
      - mysql

  app:
    build:
      context: ./app
      args:
        - APP_HOST=${APP_HOST}
        - APP_PORT=${APP_PORT}
        - API_HOST=${API_HOST}
        - API_PORT=${API_PORT}
        - JWT_SECRET=${JWT_SECRET}
    ports:
      - "${APP_PORT}:8080"
    volumes:
      - ./app/:/usr/src/app
    environment:
      - API_HOST=${API_HOST}
      - API_PORT=${API_PORT}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7.28
    command: --innodb-use-native-aio=0
    restart: always
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ./.docker/mysql/data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
